package com.jose.listacompra.ui.viewmodel

import android.util.Log
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.jose.listacompra.data.preferences.ThemePreferences
import com.jose.listacompra.domain.model.Aisle
import com.jose.listacompra.domain.model.Product
import com.jose.listacompra.domain.usecase.aisle.GetAislesBySupermarketUseCase
import com.jose.listacompra.domain.usecase.articulo.SearchArticulosUseCase
import com.jose.listacompra.domain.usecase.category.GetAllCategoriesFlowUseCase
import com.jose.listacompra.domain.usecase.history.GetPriceHistoryUseCase
import com.jose.listacompra.domain.usecase.history.GetPriceStatsUseCase
import com.jose.listacompra.domain.usecase.history.GetProductHistorySuggestionsUseCase
import com.jose.listacompra.domain.usecase.history.SavePriceHistoryUseCase
import com.jose.listacompra.domain.usecase.history.UpdateProductFrequencyUseCase
import com.jose.listacompra.domain.usecase.list.GetDefaultListUseCase
import com.jose.listacompra.domain.usecase.offers.CalculatePriceUseCase
import com.jose.listacompra.domain.usecase.offers.GetAllOffersUseCase
import com.jose.listacompra.domain.usecase.product.AddProductUseCase
import com.jose.listacompra.domain.usecase.product.DeleteProductUseCase
import com.jose.listacompra.domain.usecase.product.DeletePurchasedProductsUseCase
import com.jose.listacompra.domain.usecase.product.GetProductsByListUseCase
import com.jose.listacompra.domain.usecase.product.ToggleProductPurchasedUseCase
import com.jose.listacompra.domain.usecase.product.UpdateProductUseCase
import com.jose.listacompra.domain.usecase.supermarket.GetAllSupermarketsFlowUseCase
import com.jose.listacompra.ui.state.ProductListUiState
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import javax.inject.Inject